# Generated by Django 6.0.4 on 2026-04-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите изображение (jpg, png, gif) до 1MB', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
