# Generated by Django 6.0.4 on 2026-05-13 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('author', models.CharField(blank=True, help_text='Можно указать имя/группу', max_length=200, verbose_name='Автор (текст)')),
                ('source', models.CharField(blank=True, help_text='Ссылка на источник или авторский сайт', max_length=500, verbose_name='Источник')),
                ('privacy', models.CharField(choices=[('public', 'Публичный'), ('by_link', 'По ссылке'), ('private', 'Только владелец')], default='public', max_length=20, verbose_name='Приватность')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('allow_downloads', models.BooleanField(default=True, verbose_name='Разрешить скачивание')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор (пользователь)')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photos.photoalbum', verbose_name='Обложка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Владелец альбома')),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбомы',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('file_original', models.FileField(max_length=500, upload_to='temp/', verbose_name='Оригинал')),
                ('file_optimized', models.FileField(blank=True, null=True, upload_to='temp/', verbose_name='Оптимизированная версия')),
                ('file_thumbnail', models.FileField(blank=True, null=True, upload_to='temp/', verbose_name='Превью')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME-тип')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Размеры, вес, доп. параметры', verbose_name='Метаданные')),
                ('author', models.CharField(blank=True, help_text='Можно переопределить для элемента', max_length=200, verbose_name='Автор (текст)')),
                ('source', models.CharField(blank=True, max_length=500, verbose_name='Источник')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Альтернативный текст')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор (пользователь)')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.photoalbum', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['position', 'uploaded_at'],
            },
        ),
    ]
