# Generated by Django 6.0.4 on 2026-05-13 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='author_user',
        ),
        migrations.RemoveField(
            model_name='photoalbum',
            name='author_user',
        ),
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='Автор (элемента)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_optimized',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл (оптимизированный)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_original',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл (оригинал)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл (превью)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='source',
            field=models.URLField(blank=True, verbose_name='Источник (элемента)'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='author',
            field=models.CharField(blank=True, help_text='Свободное имя автора (группа, человек)', max_length=200, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_albums', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='source',
            field=models.URLField(blank=True, verbose_name='Источник'),
        ),
    ]
