# Generated by Django 6.0.4 on 2026-05-13 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_photo_author_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='Автор'),
        ),
    ]
