# Generated by Django 6.0.4 on 2026-05-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_uploaded_by_alter_photo_original_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
