# Generated by Django 6.0.4 on 2026-05-20 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photos.photo', verbose_name='Обложка'),
        ),
    ]
