# Generated by Django 6.0.4 on 2026-04-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Системное имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'ordering': ['name'],
                'permissions': [('can_soft_delete_directory', 'Может мягко удалять справочник'), ('can_hard_delete_directory', 'Может полностью удалять справочник'), ('can_restore_directory', 'Может восстанавливать справочник')],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('boolean', 'Да/Нет'), ('reference', 'Ссылка на другой справочник'), ('image', 'Изображение')], default='text', max_length=20, verbose_name='Тип поля')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('thumb_width', models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='Ширина миниатюры')),
                ('thumb_height', models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='Высота миниатюры')),
                ('max_size_mb', models.PositiveIntegerField(default=1, verbose_name='Макс. размер (Мб)')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='directories.directory', verbose_name='Справочник')),
                ('reference_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencing_fields', to='directories.directory', verbose_name='Справочник-источник')),
            ],
            options={
                'verbose_name': 'Поле справочника',
                'verbose_name_plural': 'Поля справочников',
                'ordering': ['directory', 'position', 'name'],
                'permissions': [('can_soft_delete_field', 'Может мягко удалять поле'), ('can_hard_delete_field', 'Может полностью удалять поле'), ('can_restore_field', 'Может восстанавливать поле')],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалена')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='directories.directory', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'Запись справочника',
                'verbose_name_plural': 'Записи справочников',
                'ordering': ['-created_at'],
                'permissions': [('can_soft_delete_record', 'Может мягко удалять запись'), ('can_hard_delete_record', 'Может полностью удалять запись'), ('can_restore_record', 'Может восстанавливать запись')],
            },
        ),
        migrations.CreateModel(
            name='RecordValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='directories.field', verbose_name='Поле')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='directories.record', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Значение поля',
                'verbose_name_plural': 'Значения полей',
                'unique_together': {('record', 'field')},
            },
        ),
    ]
