# Generated by Django 6.0.4 on 2026-04-30 14:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='test_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Тестовое содержимое'),
        ),
    ]
