# Generated by Django 6.0.4 on 2026-04-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_directory_test_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='test_content',
        ),
    ]
