# Generated by Django 6.0.4 on 2026-05-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0003_remove_directory_test_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Для типа "Короткая строка": максимальное количество символов (по умолчанию 255)', null=True, verbose_name='Максимальная длина'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('string', 'Короткая строка'), ('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('boolean', 'Да/Нет'), ('reference', 'Ссылка на другой справочник'), ('image', 'Изображение')], default='text', max_length=20, verbose_name='Тип поля'),
        ),
    ]
