# Generated by Django 6.0.4 on 2026-05-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0004_field_max_length_alter_field_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Использовать как значение по умолчанию'),
        ),
    ]
