# Generated by Django 6.0.4 on 2026-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0007_add_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='slug',
            field=models.SlugField(blank=True, help_text='Уникальный идентификатор для URL (генерируется автоматически)', max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
