# Generated by Django 6.0.4 on 2026-05-04 14:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0004_field_max_length_alter_field_field_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Создана')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='План (часы)')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Факт (часы)')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Slug')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assignee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'directory__slug': 'task_priorities', 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.record', verbose_name='Приоритет')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'directory__slug': 'task_statuses', 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.record', verbose_name='Статус')),
                ('task_type', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'directory__slug': 'task_types', 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.record', verbose_name='Тип задачи')),
            ],
            options={
                'verbose_name': 'historical Задача',
                'verbose_name_plural': 'historical Задачи',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='План (часы)')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Факт (часы)')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('priority', models.ForeignKey(limit_choices_to={'directory__slug': 'task_priorities', 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_as_priority', to='directories.record', verbose_name='Приоритет')),
                ('status', models.ForeignKey(limit_choices_to={'directory__slug': 'task_statuses', 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_as_status', to='directories.record', verbose_name='Статус')),
                ('task_type', models.ForeignKey(limit_choices_to={'directory__slug': 'task_types', 'is_deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_as_type', to='directories.record', verbose_name='Тип задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=1, verbose_name='Голос (+1/-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
                'unique_together': {('task', 'user')},
            },
        ),
    ]
